// AUTH ACTIONS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

// ERROR ACTIONS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// BLOG ACTIONS
export const BLOG_LOADING = 'BLOG_LOADING';
export const BLOGS_LOADED = 'BLOGS_LOADED';
export const BLOG_LOADED = 'BLOG_LOADED';
export const BLOGS_LOADED_BY_CATEGORY = 'BLOGS_LOADED_BY_CATEGORY';
export const ADD_BLOG = 'ADD_BLOG';
export const EDIT_BLOG = 'EDIT_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const BLOG_ERROR = 'BLOG_ERROR';
